<a href="https://colab.research.google.com/github/Deeva2601/Retail_Sales_Analysis/blob/main/Superstore_cleaned.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"/content/Raw_Superstore_Data.csv")
df.head(5)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,NaN,NaN,0.3
1,CA-2017-129684,Claire Gute,Consumer,South,NaN,Office Supplies,Apple iPhone 7,240.59,6.0,0.0
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,NaN,Staples Notebook,676.50,5.0,0.0
3,CA-2018-122872,Sara Parker,NaN,East,Washington,NaN,Hon Deluxe Fabric Chair,NaN,7.0,0.1
4,CA-2018-185789,Sara Parker,NaN,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.0,0.3

In [3]:
df.columns
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          255 non-null    object
 1   Customer Name     234 non-null    object
 2   Segment           187 non-null    object
 3   Region            196 non-null    object
 4   City              218 non-null    object
 5   Product Category  187 non-null    object
 6   Product Name      223 non-null    object
 7   Sales             223 non-null    float64
 8   Quantity          234 non-null    float64
 9   Discount          201 non-null    float64
dtypes: float64(3), object(7)
memory usage: 20.1+ KB

            Sales    Quantity    Discount
count  223.000000  234.000000  201.000000
mean   505.741300    5.709402    0.220896
std    296.766739    2.964916    0.178497
min     14.220000    1.000000    0.000000
25%    240.455000    3.000000    0.100000
50%    511.560000    6.000000    0.200000
75%    764.085000    8.000000    0.300000
max    999.280000   10.000000    0.500000

In [4]:
df.isnull().sum()

Order ID             0
Customer Name       21
Segment             68
Region              59
City                37
Product Category    68
Product Name        32
Sales               32
Quantity            21
Discount            54
dtype: int64

In [5]:
df['Sales'].fillna(df['Sales'].median(),inplace = True)
df['Quantity'].fillna(df['Quantity'].mean(),inplace = True)
df['Discount'].fillna(df['Discount'].mean(),inplace = True)

/tmp/ipykernel_1771/190605659.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sales'].fillna(df['Sales'].median(),inplace = True)
/tmp/ipykernel_1771/190605659.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(),inplace = True)
/tmp/ipykernel_1771/190605659.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].fillna(df['Discount'].mean(),inplace = True)

In [6]:
df.head(7)

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.3
1,CA-2017-129684,Claire Gute,Consumer,South,NaN,Office Supplies,Apple iPhone 7,240.59,6.000000,0.0
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,NaN,Staples Notebook,676.50,5.000000,0.0
3,CA-2018-122872,Sara Parker,NaN,East,Washington,NaN,Hon Deluxe Fabric Chair,511.56,7.000000,0.1
4,CA-2018-185789,Sara Parker,NaN,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.3
5,CA-2014-116775,John Lee,Corporate,Central,Seattle,Technology,NaN,511.56,5.709402,0.5
6,CA-2016-120470,Laila Wilson,Consumer,South,Washington,Technology,Bush Somerset Collection,746.15,8.000000,0.5

In [7]:
df['Segment'].fillna(df['Segment'].mode())

0         Consumer
1         Consumer
2         Consumer
3              NaN
4              NaN
          ...
250    Home Office
251            NaN
252       Consumer
253            NaN
254            NaN
Name: Segment, Length: 255, dtype: object

In [8]:
df.isnull().sum()

Order ID             0
Customer Name       21
Segment             68
Region              59
City                37
Product Category    68
Product Name        32
Sales                0
Quantity             0
Discount             0
dtype: int64

In [9]:
categorial_cols = ['Customer Name','Segment','Region','City','Product Category','Product Name']
for cols in categorial_cols:
  df[cols].fillna(df[cols].mode()[0],inplace = True)

/tmp/ipykernel_1771/2326645637.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(df[cols].mode()[0],inplace = True)

In [10]:
categorical_null_counts = df[categorial_cols].isnull().sum()

In [11]:
df.isnull().sum()

Order ID            0
Customer Name       0
Segment             0
Region              0
City                0
Product Category    0
Product Name        0
Sales               0
Quantity            0
Discount            0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(10)

In [17]:
df.drop_duplicates()

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.3
1,CA-2017-129684,Claire Gute,Consumer,South,Seattle,Office Supplies,Apple iPhone 7,240.59,6.000000,0.0
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,Technology,Staples Notebook,676.50,5.000000,0.0
3,CA-2018-122872,Sara Parker,Home Office,East,Washington,Technology,Hon Deluxe Fabric Chair,511.56,7.000000,0.1
4,CA-2018-185789,Sara Parker,Home Office,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.3
...,...,...,...,...,...,...,...,...,...,...
240,CA-2017-167364,Laila Wilson,Home Office,East,New York,Office Supplies,Canon EOS Rebel,170.25,7.000000,0.1
241,CA-2017-120093,Mike Johnson,Consumer,East,Seattle,Technology,Staples Notebook,204.10,4.000000,0.2
242,CA-2017-128091,Darrin Van Huff,Consumer,Central,Washington,Technology,Bush Somerset Collection,883.06,5.709402,0.2
243,CA-2015-106588,Sean O'Dell,Home Office,Central,Seattle,Furniture,Bush Somerset Collection,641.73,10.000000,0.2
244,CA-2014-161826,Emily Phan,Home Office,West,Washington,Technology,Hon Deluxe Fabric Chair,91.53,4.000000,0.3

In [18]:
df[df.duplicated()]

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
245,CA-2017-140807,Darrin Van Huff,Consumer,East,Philadelphia,Technology,Staples Notebook,883.30,8.0,0.100000
246,CA-2018-127940,Mike Johnson,Corporate,Central,Los Angeles,Technology,Hon Deluxe Fabric Chair,961.56,3.0,0.500000
247,CA-2015-183074,Sara Parker,Consumer,East,Philadelphia,Furniture,Hon Deluxe Fabric Chair,569.45,9.0,0.200000
248,CA-2017-132445,Darrin Van Huff,Home Office,East,Seattle,Technology,Fellowes Banks Janalo,558.41,10.0,0.220896
249,CA-2018-145827,Sean O'Dell,Home Office,East,Seattle,Office Supplies,Hon Deluxe Fabric Chair,801.75,10.0,0.100000
250,CA-2014-109974,Darrin Van Huff,Home Office,East,Los Angeles,Technology,Staples Notebook,968.61,6.0,0.200000
251,CA-2014-107029,Mike Johnson,Home Office,West,Washington,Furniture,Apple iPhone 7,831.97,6.0,0.000000
252,CA-2016-192386,Sara Parker,Consumer,Central,New York,Technology,Fellowes Banks Janalo,966.25,8.0,0.220896
253,CA-2014-140007,Sara Parker,Home Office,East,Philadelphia,Office Supplies,Canon EOS Rebel,295.53,6.0,0.220896
254,CA-2018-188814,Evan Reichert,Home Office,East,Seattle,Furniture,Fellowes Banks Janalo,212.25,4.0,0.500000

In [19]:
df[df.duplicated(subset=['Order ID'])]

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount
245,CA-2017-140807,Darrin Van Huff,Consumer,East,Philadelphia,Technology,Staples Notebook,883.30,8.0,0.100000
246,CA-2018-127940,Mike Johnson,Corporate,Central,Los Angeles,Technology,Hon Deluxe Fabric Chair,961.56,3.0,0.500000
247,CA-2015-183074,Sara Parker,Consumer,East,Philadelphia,Furniture,Hon Deluxe Fabric Chair,569.45,9.0,0.200000
248,CA-2017-132445,Darrin Van Huff,Home Office,East,Seattle,Technology,Fellowes Banks Janalo,558.41,10.0,0.220896
249,CA-2018-145827,Sean O'Dell,Home Office,East,Seattle,Office Supplies,Hon Deluxe Fabric Chair,801.75,10.0,0.100000
250,CA-2014-109974,Darrin Van Huff,Home Office,East,Los Angeles,Technology,Staples Notebook,968.61,6.0,0.200000
251,CA-2014-107029,Mike Johnson,Home Office,West,Washington,Furniture,Apple iPhone 7,831.97,6.0,0.000000
252,CA-2016-192386,Sara Parker,Consumer,Central,New York,Technology,Fellowes Banks Janalo,966.25,8.0,0.220896
253,CA-2014-140007,Sara Parker,Home Office,East,Philadelphia,Office Supplies,Canon EOS Rebel,295.53,6.0,0.220896
254,CA-2018-188814,Evan Reichert,Home Office,East,Seattle,Furniture,Fellowes Banks Janalo,212.25,4.0,0.500000

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
print("After removal:", df.duplicated().sum())

After removal: 0

In [23]:
df['Month'] = [i%12+1 for i in range(len(df))]
df['Year'] = 2020

df['Date'] = pd.to_datetime(df['Year'].astype(str) + '-' + df['Month'].astype(str) + '-01')

df.drop(['Month', 'Year'], axis=1, inplace=True)

In [24]:
df

,Order ID,Customer Name,Segment,Region,City,Product Category,Product Name,Sales,Quantity,Discount,Date
0,CA-2017-193512,Sean O'Dell,Consumer,South,Seattle,Office Supplies,Staples Notebook,511.56,5.709402,0.3,2020-01-01
1,CA-2017-129684,Claire Gute,Consumer,South,Seattle,Office Supplies,Apple iPhone 7,240.59,6.000000,0.0,2020-02-01
2,CA-2017-102220,Sean O'Dell,Consumer,East,Houston,Technology,Staples Notebook,676.50,5.000000,0.0,2020-03-01
3,CA-2018-122872,Sara Parker,Home Office,East,Washington,Technology,Hon Deluxe Fabric Chair,511.56,7.000000,0.1,2020-04-01
4,CA-2018-185789,Sara Parker,Home Office,South,Phoenix,Furniture,Canon EOS Rebel,68.00,7.000000,0.3,2020-05-01
...,...,...,...,...,...,...,...,...,...,...,...
240,CA-2017-167364,Laila Wilson,Home Office,East,New York,Office Supplies,Canon EOS Rebel,170.25,7.000000,0.1,2020-01-01
241,CA-2017-120093,Mike Johnson,Consumer,East,Seattle,Technology,Staples Notebook,204.10,4.000000,0.2,2020-02-01
242,CA-2017-128091,Darrin Van Huff,Consumer,Central,Washington,Technology,Bush Somerset Collection,883.06,5.709402,0.2,2020-03-01
243,CA-2015-106588,Sean O'Dell,Home Office,Central,Seattle,Furniture,Bush Somerset Collection,641.73,10.000000,0.2,2020-04-01
244,CA-2014-161826,Emily Phan,Home Office,West,Washington,Technology,Hon Deluxe Fabric Chair,91.53,4.000000,0.3,2020-05-01

In [25]:
df.to_csv("Superstore_Cleaned.csv", index=False)

In [26]:
from google.colab import files
files.download("Superstore_Cleaned.csv")